version: '3.4'

services:
  jaeger-host:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
  
  first-api:
    build: 
      context: ./FirstApi
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:7000:5001"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://*:5001"
      - "Settings__ApiUrl=http://second-api:5002"
      - "Settings__JaegerHost=jaeger-host"
  
  second-api:
    build: 
      context: ./SecondApi
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:7001:5002"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://*:5002"
      - "Settings__JaegerHost=jaeger-host"
  
  web-app:
    build:
      context: ./WebApp
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:7100:5100"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://*:5100"
      - "Settings__ApiUrl=http://first-api:5001"
      - "Settings__JaegerHost=jaeger-host"

      